"""
src/report_writer.py — 报告生成（从 raw.json 素材包 → Markdown）
"""
import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, "/Users/lobster/.openclaw/workspace/skills/reflexion-ensemble")
from reflexion.providers import llm_call

_DISCLAIMER = """> This report is generated by PropertyPrism AI and is intended for
> informational purposes only. It does not constitute financial,
> legal, or investment advice. All findings should be independently
> verified before making any lending or investment decision.
> Government data (FEMA, County Assessor) sourced via public REST APIs
> and is provided as-is. Confirm all data with qualified professionals
> before making any lending decision."""


def _render_source(s) -> str:
    """渲染单个 source 条目，verified=False 时添加 ⚠️ UNVERIFIED 标注。"""
    if isinstance(s, str):
        return f"- {s}"

    url = s.get("url", "")
    raw_quote = s.get("raw_quote", "")
    data_type = s.get("data_type", "")
    verified = s.get("verified")

    text = url or "(no url)"
    if raw_quote:
        text += f' — "{raw_quote}"'
    if data_type:
        text += f" [{data_type}]"
    if verified is False:
        text += " ⚠️ UNVERIFIED"

    return f"- {text}"


def _fmt_money(val) -> str:
    if val is None:
        return "N/A"
    try:
        return f"${int(val):,}"
    except (ValueError, TypeError):
        return str(val)


def _render_gov_data_section(gov_data: dict) -> list[str]:
    """Render government data with CONFIRMED/PARTIAL/NOT_CONFIGURED labels."""
    lines = [
        "## Government Data (Track A — Pre-Fetched)",
        "",
        "| Source | Status | Key Data |",
        "|--------|--------|----------|",
    ]

    fema = gov_data.get("fema", {})
    if fema.get("status") == "SUCCESS":
        sfha = "YES ⚠️" if fema.get("in_sfha") else "NO"
        lines.append(
            f"| FEMA Flood Zone | ✅ CONFIRMED | Zone {fema.get('flood_zone', 'N/A')} — "
            f"In SFHA: {sfha} |"
        )
    elif fema.get("status") == "FAILED":
        lines.append(f"| FEMA Flood Zone | ❌ FAILED | {fema.get('error', 'query failed')} |")
    else:
        lines.append("| FEMA Flood Zone | ⚠️ NOT RUN | — |")

    assessor = gov_data.get("assessor", {})
    if assessor.get("status") == "SUCCESS":
        owner = assessor.get("owner", "N/A")
        parcel = assessor.get("parcel_number", "N/A")
        assessed = _fmt_money(assessor.get("assessed_value"))
        lines.append(
            f"| County Assessor | ✅ CONFIRMED | Owner: {owner}, Parcel: {parcel}, "
            f"Assessed: {assessed} |"
        )
    elif assessor.get("status") == "NOT_CONFIGURED":
        lines.append("| County Assessor | ⚪ NOT CONFIGURED | Market not supported |")
    elif assessor.get("status") == "FAILED":
        lines.append(f"| County Assessor | ❌ FAILED | {assessor.get('error', 'query failed')} |")

    treasurer = gov_data.get("treasurer", {})
    if treasurer.get("status") == "SUCCESS":
        tax_status = treasurer.get("tax_status", "N/A")
        lines.append(f"| County Treasurer | ✅ CONFIRMED | Tax Status: {tax_status} |")
    elif treasurer.get("status") == "SKIPPED_DEPENDENCY":
        lines.append("| County Treasurer | ⏭️ SKIPPED | Depends on Assessor (not available) |")
    elif treasurer.get("status") == "NEEDS_TESTING":
        lines.append("| County Treasurer | 🔬 NEEDS TESTING | Interface pending validation |")
    elif treasurer.get("status") == "NOT_CONFIGURED":
        lines.append("| County Treasurer | ⚪ NOT CONFIGURED | Market not supported |")

    recorder = gov_data.get("recorder", {})
    if recorder.get("status") == "NOT_CONFIGURED":
        lines.append(
            "| County Recorder | ⚠️ PARTIAL | Cloudflare protection — AI fallback via jina_read |"
        )

    lines.append("")
    return lines


def write_report(bundle: dict) -> str:
    """
    从 raw.json 素材包生成 Markdown 报告。

    Args:
        bundle: build_raw_bundle() 返回的素材包 dict

    Returns:
        Markdown 格式报告字符串
    """
    property_data = bundle.get("property_data", {})
    macro = bundle.get("macro", {})
    micro = bundle.get("micro", {})
    synthesis = bundle.get("synthesis")
    gov_data = bundle.get("gov_data")
    generated_at = bundle.get("generated_at", date.today().strftime("%Y-%m-%d"))

    address = property_data.get("address", "Unknown Address")
    risk_level = macro.get("risk_level", "UNKNOWN")

    judge_verdict = (synthesis or {}).get("judge_verdict", {})
    micro_verdict = micro.get("verdict", {})

    if judge_verdict:
        action = judge_verdict.get("final_action", "UNKNOWN")
        confidence = judge_verdict.get("confidence", "UNKNOWN")
        executive_summary = judge_verdict.get("executive_summary", "")
    else:
        action = micro_verdict.get("recommended_action", "UNKNOWN")
        confidence = micro_verdict.get("confidence", "UNKNOWN")
        executive_summary = micro_verdict.get("one_line_summary", "")

    kill_switch = micro_verdict.get("kill_switch", False)

    action_emoji = "🔴" if action == "KILL" else ("🟡" if action == "CONDITIONAL_PURSUE" else "🟢")
    risk_emoji = {
        "LOW": "🟢", "MODERATE": "🟡", "HIGH": "🟠", "CRITICAL": "🔴"
    }.get(risk_level, "⚪")

    lines = []

    # ── Cover ──────────────────────────────────────────────────────────────────
    lines += [
        "# FieldLens Risk Intelligence Report",
        "",
        f"**Property:** {address}",
        f"**Report Date:** {generated_at}",
        f"**Area Risk:** {risk_emoji} {risk_level}",
        f"**Verdict:** {action_emoji} {action} (Confidence: {confidence})",
        "",
        "---",
        "",
    ]

    # ── Executive Summary ──────────────────────────────────────────────────────
    lines += ["## Executive Summary", ""]
    if kill_switch:
        lines.append("🔴 **KILL SWITCH TRIGGERED**")
        lines.append("")
    lines += [
        executive_summary if executive_summary else "_No executive summary available._",
        "",
        "---",
        "",
    ]

    # ── Government Data (Track A) ──────────────────────────────────────────────
    if gov_data:
        lines += _render_gov_data_section(gov_data)
        lines += ["---", ""]

    # ── Key Insights (Layer 3 Cross-Reference) ─────────────────────────────────
    if synthesis:
        cross_insights = synthesis.get("cross_insights", [])
        lines += [
            "## Key Insights",
            "",
            "_Cross-layer analysis: what the data implies when combined._",
            "",
        ]
        for insight in cross_insights:
            severity = insight.get("severity", "")
            sev_emoji = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(severity, "⚪")
            lines += [
                f"### {sev_emoji} {insight.get('title', 'Insight')}",
                "",
                "**Data Basis:**",
            ]
            for dp in insight.get("data_points", []):
                lines.append(f"- {dp}")
            lines += [
                "",
                f"**Reasoning:** {insight.get('reasoning', '')}",
                "",
                f"**For the Lender:** {insight.get('so_what', '')}",
                "",
                f"**Estimated Impact:** {insight.get('estimated_impact', 'N/A')}",
                "",
            ]
        lines += ["---", ""]

    # ── Risk Debate Summary ────────────────────────────────────────────────────
    if synthesis:
        blue = synthesis.get("blue_team", {})
        red = synthesis.get("red_team", {})
        jv = synthesis.get("judge_verdict", {})

        lines += ["## Risk Debate Summary", "", "### 🟢 Bull Case", ""]
        for arg in blue.get("bull_arguments", []):
            lines.append(f"- {arg}")
        if blue.get("recommended_ltv"):
            lines.append(f"- **Recommended LTV:** {blue['recommended_ltv']}")
        if blue.get("exit_strategy"):
            lines.append(f"- **Exit Strategy:** {blue['exit_strategy']}")
        lines.append("")

        lines += ["### 🔴 Bear Case", ""]
        for arg in red.get("bear_arguments", []):
            lines.append(f"- {arg}")
        wcs = red.get("worst_case_scenario", {})
        if isinstance(wcs, dict) and wcs.get("lender_loss_estimate"):
            lines.append(f"- **Worst-Case Loss:** {wcs['lender_loss_estimate']}")
        elif isinstance(wcs, str) and wcs:
            lines.append(f"- **Worst Case:** {wcs}")
        lines.append("")

        lines += [
            "### ⚖️ Committee Verdict",
            "",
            f"**Final Action:** {action_emoji} {action}",
            f"**Confidence:** {confidence}",
            f"**Winning Side:** {jv.get('winning_side', 'N/A')}",
            "",
        ]

        conditions = jv.get("conditions_to_pursue", [])
        if conditions:
            lines += ["**Conditions to Pursue:**", ""]
            for c in conditions:
                lines.append(f"- {c}")
            lines.append("")

        unresolved = jv.get("unresolved_risks", [])
        if unresolved:
            lines += ["**Unresolved Risks:**", ""]
            for r in unresolved:
                lines.append(f"- ⚠️ {r}")
            lines.append("")

        lines += ["---", ""]

    # ── Supporting Evidence ────────────────────────────────────────────────────
    lines += ["## Supporting Evidence", ""]

    lines += [
        "### Property Snapshot",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Price | {_fmt_money(property_data.get('price'))} |",
        f"| Beds / Baths | {property_data.get('bedrooms', 'N/A')} bd / {property_data.get('bathrooms', 'N/A')} ba |",
        f"| Year Built | {property_data.get('yearBuilt', 'N/A')} |",
        f"| Home Type | {property_data.get('homeType', 'N/A')} |",
        f"| Living Area | {property_data.get('livingArea', 'N/A')} sqft |",
        f"| Lot Size | {property_data.get('lotSize', 'N/A')} sqft |",
        f"| Days on Market | {property_data.get('daysOnZillow', 'N/A')} |",
        f"| Rent Zestimate | {_fmt_money(property_data.get('rentZestimate'))} /mo |",
        f"| Annual Taxes | {_fmt_money(property_data.get('taxAnnualAmount'))} |",
        f"| HOA Fee | {_fmt_money(property_data.get('hoaFee'))} /mo |",
        "",
    ]

    schools = property_data.get("schoolRating", [])
    if schools:
        lines += ["**Schools:**", ""]
        for s in schools:
            lines.append(f"- {s}")
        lines.append("")

    price_history = property_data.get("priceHistory", [])
    if price_history:
        lines += ["**Price History:**", ""]
        for ph in price_history:
            lines.append(
                f"- {ph.get('date', 'N/A')}: {_fmt_money(ph.get('price'))} — {ph.get('event', '')}"
            )
        lines.append("")

    lines += [
        "### Area Analysis",
        "",
        f"**Risk Level:** {risk_emoji} {risk_level}",
        f"**Rationale:** {macro.get('risk_rationale', 'N/A')}",
        "",
        "**Key Findings:**",
        "",
    ]
    for finding in macro.get("key_findings", []):
        lines.append(f"- {finding}")
    lines.append("")

    lines += [
        "| Domain | Assessment |",
        "|--------|------------|",
        f"| Crime & Safety | {macro.get('crime_summary', 'N/A')} |",
        f"| Market Trend | {macro.get('market_trend', 'N/A')} |",
        f"| Regulatory Risks | {macro.get('regulatory_risks', 'N/A')} |",
        f"| Infrastructure & Environment | {macro.get('infrastructure_risks', 'N/A')} |",
        f"| Macro Signals | {macro.get('macro_signals', 'N/A')} |",
        "",
    ]

    for f in macro.get("red_flags", []):
        lines.append(f"- 🚩 {f}")
    if macro.get("red_flags"):
        lines.append("")

    for g in macro.get("green_signals", []):
        lines.append(f"- ✅ {g}")
    if macro.get("green_signals"):
        lines.append("")

    lines += ["### Property Forensics", ""]

    phases = micro.get("phase_results", {})
    phase_configs = [
        ("phase1_ownership", "Phase 1 — Ownership Provenance"),
        ("phase2_permits", "Phase 2 — Permit Audit"),
        ("phase3_crime", "Phase 3 — Street-Level Crime"),
        ("phase4_infrastructure", "Phase 4 — Infrastructure & Environment"),
        ("phase5_rent", "Phase 5 — Rent Reality Check"),
        ("phase6_regulatory", "Phase 6 — Market & Regulatory Risk"),
    ]

    for key, title in phase_configs:
        phase = phases.get(key, {})
        lines += [f"#### {title}", ""]
        lines.append(phase.get("findings", "No findings recorded."))
        lines.append("")

        for r in phase.get("red_flags", []):
            lines.append(f"- 🚩 {r}")
        if phase.get("red_flags"):
            lines.append("")

        cross_note = phase.get("cross_reference_note", "")
        if cross_note:
            lines.append(f"_Cross-reference: {cross_note}_")
            lines.append("")

    lines += [
        "**Layer 2 Verdict:**",
        "",
        f"- Recommended Action: {micro_verdict.get('recommended_action', 'N/A')}",
        f"- Confidence: {micro_verdict.get('confidence', 'N/A')}",
        "",
    ]

    for r in micro.get("top_risks", []):
        lines.append(f"- ⚠️ {r}")
    if micro.get("top_risks"):
        lines.append("")

    for s in micro.get("top_strengths", []):
        lines.append(f"- ✅ {s}")
    if micro.get("top_strengths"):
        lines.append("")

    all_sources = list(macro.get("sources", [])) + list(micro.get("sources", []))
    if all_sources:
        lines += ["**Sources:**", ""]
        for s in all_sources:
            lines.append(_render_source(s))
        lines.append("")

    lines += ["---", ""]

    # ── Data Gaps ──────────────────────────────────────────────────────────────
    all_gaps = list(micro.get("data_gaps", [])) + list(macro.get("unknowns", []))
    if all_gaps:
        lines += ["## Data Gaps & Limitations", ""]
        for gap in all_gaps:
            lines.append(f"- {gap}")
        lines += ["", "---", ""]

    # ── Disclaimer ─────────────────────────────────────────────────────────────
    lines += ["## Disclaimer", "", _DISCLAIMER, ""]

    return "\n".join(lines)


def write_report_from_file(path: str) -> str:
    """从 raw.json 文件路径读取素材包并生成报告。"""
    bundle = json.loads(Path(path).read_text(encoding="utf-8"))
    return write_report(bundle)


def write_report_zh(bundle: dict) -> str:
    """
    生成中文速览版报告（用 Sonnet 翻译关键段落）。

    Args:
        bundle: build_raw_bundle() 返回的素材包 dict

    Returns:
        中文 Markdown 报告字符串
    """
    property_data = bundle.get("property_data", {})
    macro = bundle.get("macro", {})
    micro = bundle.get("micro", {})
    synthesis = bundle.get("synthesis") or {}

    judge_verdict = synthesis.get("judge_verdict", {})
    micro_verdict = micro.get("verdict", {})
    action = judge_verdict.get("final_action") or micro_verdict.get("recommended_action", "UNKNOWN")
    executive_summary = judge_verdict.get("executive_summary") or micro_verdict.get("one_line_summary", "")

    key_findings = macro.get("key_findings", [])[:3]
    cross_insights = [i.get("title", "") for i in synthesis.get("cross_insights", [])[:3]]

    content_to_translate = f"""
Property: {property_data.get('address', 'N/A')}
Action: {action}
Executive Summary: {executive_summary}
Key Area Findings: {'; '.join(key_findings)}
Key Insights: {'; '.join(cross_insights)}
Risk Level: {macro.get('risk_level', 'N/A')}
"""

    messages = [{
        "role": "user",
        "content": (
            "请将以下房产风险报告关键信息翻译为中文，保留所有数据和专业术语，"
            "输出简洁的中文速览版（不超过300字）：\n\n"
            + content_to_translate
        ),
    }]

    response = llm_call(
        provider="openclaw",
        model="reflexion-sonnet",
        messages=messages,
        max_tokens=1000,
    )

    return response["content"]
